export const actionTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SIGNUP: "SIGNUP",
    LOADER_ON: "LOADER_ON",
    LOADER_OFF: "LOADER_OFF",
    COUNTRY_LIST :"COUNTRY_LIST",
    FETCH_DELIVER_ORDER:"FETCH_DELIVER_ORDER",
    FETCH_RETURN_ORDER:'FETCH_RETURN_ORDER'
}