export const actionTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SIGNUP: "SIGNUP",
    LOADER_ON: "LOADER_ON",
    LOADER_OFF: "LOADER_OFF",
    COUNTRY_LIST :"COUNTRY_LIST",
    FETCH_DELIVER_ORDER:"FETCH_DELIVER_ORDER",
    FETCH_RETURN_ORDER:'FETCH_RETURN_ORDER',
    FETCH_REASON_LIST:'FETCH_REASON_LIST',
    FETCH_ORDER_DETAIL:"FETCH_ORDER_DETAIL",
    ACCEPT_ORDER:"ACCEPT_ORDER",
    RESET_ORDER_DETAIL:"RESET_ORDER_DETAIL",
    DELEVIERY_FAILED_POST:"DELEVIERY_FAILED_POST"
}