export var arabic =
{
    loginPageHeader: "Baytonia Special",
    labelLogin: "تسجيل الدخول",
    labelEmailUsername: "البريد الالكتروني/اسم المستخدم",
    passwordLabel: "كلمة السر",
    labelLoginButton: "تسجيل الدخول",
    forgotPasswordLabel: "نسيت كلمة السر؟",
    emailOrUsernameCannotBeEmptyLabel: "لا يمكن ترك خانة الايميل فارغة",
    enterValidEmailLabel: "الرجاء ادخال ايميل صحيح",
    passwordCannotBeEmptyLabel: "لا يمكن ترك كلمة السر فارغة",
    pleaseWaitTextLabel: "الرجاء الانتظار",
    loadingTextLabel: "تحميل",
    emailCannotBeEmptyLabel: "لا يمكن ترك خانة الايميل فارغة",
    PressBackAgainToExitTheApplicationLabel: "ارجع للخلف للخروج من التطبيق",
    LinkSentLabel: "تم ارسال الرابط",
    RequestFailedLabel: "تم رفض الطلب",
    ForgotPasswordRequestFailMessageLabel: "تأكد ان الايميل الذي تم إدخاله صحيح لتعيين كلمة المرور",
    EmailAddressLabel: "البريد الالكتروني",
    CancelButtonLabel: "إلغاء",
    OkButtonLabel: "موافق",
    ForgotPasswordDialogTitle: "نسيت كلمة السر",
    ForgotPasswordDialogDescription: "الرجاء ادخال الايميل لتعيين كلمة المرور",
    DeliveryBoyStatusPrefixLabel: "أنت ",
    ChangeStatusLabel: "تغيير الحالة",
    AssignedOrderLabel: "قبول طلبات",
    AcceptOrderLabel: "طلبات في انتظار التوصيل",
    DeliveredOrderLabel: "طلبات تم توصيلها",
    InvoicedOrderLabel: "طلبات مفوترة",
    DashboardOrdersLabel: "جميع الطلبات",
    LogoutLabel: "تسجيل الخروج",
    LogoutAlertTitle: "تسجيل الخروج",
    LogoutAlertBody: "هل ترغب بتسجيل الخروج؟",
    LogoutAlertSuccessButtonLabel: "نعم",
    LogoutSuccessfulMessage: "تم تسجيل الخروج",
    BackButtonLabel: "الرجوع",
    DashboardPageTitle: "الصفحة الرئيسية",
    OrderDetailsPageTitle: "تفاصيل الطلب",
    DrawerDashboardLabel: "الصفحة الرئيسية",
    DrawerOrdersLabel: "طلبات",
    DrawerSettingsLabel: "الإعدادات",
    EmptyOrderListPageMessage: "لا يوجد شيء هنا",
    OrderNumberPrefix: "طلبات #",
    OrderDatePrefix: " تاريخ الطلب :",
    DenyOrderAlertTitle: "رفض الطلب",
    DenyOrderAlertBody: "هل تريد رفض الطلب؟",
    DenyOrderAlertSuccessButtonLabel: "نعم",
    EmptyorderDetailsPageMessage: "How Did you land here ? \nThere\'s something wrong \nEither Go Back or if you are 100% sure this order belongs to you then you can contact the seller/administrator of the Website ",
    OrderNameLabelPrefix: "Order Name : ",
    OrderIdTextLabelPrefix: 'Order Id : ',
    PickingIdTextLabelPrefix: 'Picking Id : ',
    AssignDateTextLabelPrefix: 'Date & Time : ',
    OrderDeliveryAddressLabel: "العنوان ",
    OrderDetailsTextLabel: 'تفاصيل الطلب',
    CustomerDetailsTextLabel: 'تفاصيل العميل',
    ProductDetailsTextLabel: 'قائمة المنتجات',
    ProductNameLabel: 'Name : ',
    QtyToDeliverLabel: 'Qty : ',
    AcceptorderButtonLabel: "قبول الطلب",
    DenyOrderButtonLabel: "رفض الطلب",
    ShowonMapLabel: "مشاهدة على الخريطة",
    MapRoutePageHeaderLabel: "تفاصيل عنوان التوصيل",
    DeliveryLocationNotAvailable: "Sorry, Currently Delivery Location is not available",
    LocationPermissionTitle: 'Location Permission',
    LocationPermissionBody: "Location Permission Required in order to locate you on Map ",
    CurrentLocationNotAvailable: "Your Current Location is not available.",
    DeliveryAddressMapMarkerTitle: "عنوان التوصيل",
    DeliveryBoyMapMarkerTitle: "موقعي",
    StartNavigation: "Start Navigation",
    OrderDeliveredButtonLabel: "تم توصيل الطلب",
    VerifyOTP: "تحقق من الرمز",
    EnterDeliveryOTP: "أدخل رمز التأكيد",
    DeliveryOTP: "رمز تأكيد التوصيل",
    OTPCannotBeEmptyLabel: "يجب إدخال الرمز",
    EnterValidOTPValue: "الرجاء إدخال رمز صحيح",
    SettingsPageTitle: "الإعدادات",
    AllpickingsPageTitle: "جميع الطلبات",
    OrderDetailsPageAmountLabel: "المبلغ: ",
    OrderDetailsPageStatusLabel: "الحالة",
    OrderDetailsTelephoneLabel: "رقم الجوال",
    OrderDetailsMobileLabel: "رقم الجوال",
    OrderDetailsEmailLabel: "الأيميل",
    OrderDetailsSubtotalLabel: "المجموع الجزئي",
    OrderDetailsTaxLabel: "ضريبة",
    OrderDetailsGrandTotalLabel: "المجموع الكلي",
    AmountDueLabel: "مبلغ مستحق",
    TotalOrdersDeliveredLabel: "طلب تم توصيله",
    TotalEarningsReceivedLabel: "مجموع الأرباح",
    TotalNumberOfBoxes: " : عدد الكراتين",
    CustomerContact: "معلومات العميل",
    arabic: "عربي",
    english: "الإنجليزية",
    OrderReturned: 'طلب تم ترجيعه',
    MyOrders: 'طلباتي',
    DELIVERY: 'توصيل',
    RETURN: 'ترجيع',
    AssignedOrders: 'قبول طلبات',
    AcceptedOrders: 'طلبات في انتظار التسليم',
    CompletedOrders: 'طلبات تم توصيلها',
    ReturnOrder: "مرتجع",
    Order: ' طلب',
    Return: "ترجيع",
    OrderDate:"تاريخ",
    VendorPos: "Vendor POs",
    RECEIVING:"RECEIVING"
}

export var english = {
    loginPageHeader: "Baytonia Special",
    labelLogin: "Login",
    labelEmailUsername: "Email/Username",
    passwordLabel: "Password",
    labelLoginButton: "LOG IN",
    forgotPasswordLabel: "Forgot Password ?",
    emailOrUsernameCannotBeEmptyLabel: "Email/Username cannot be empty",
    enterValidEmailLabel: "Please enter a valid email",
    passwordCannotBeEmptyLabel: "Password cannot be empty",
    pleaseWaitTextLabel: "Please Wait",
    loadingTextLabel: "Loading ...",
    emailCannotBeEmptyLabel: "Email cannot be empty",
    PressBackAgainToExitTheApplicationLabel: "Press back again to exit the application",
    LinkSentLabel: "Link Sent",
    RequestFailedLabel: "Request Failed",
    ForgotPasswordRequestFailMessageLabel: "Please make sure that you have used an already registered and correct email for resetting password request",
    EmailAddressLabel: "Email Address",
    CancelButtonLabel: "Cancel",
    OkButtonLabel: "OK",
    ForgotPasswordDialogTitle: "Forgot Password",
    ForgotPasswordDialogDescription: "Please enter your email address below. You will recieve an email to change your password ",
    DeliveryBoyStatusPrefixLabel: "You are ",
    ChangeStatusLabel: "Change Status",
    AssignedOrderLabel: "Accept Orders",
    AcceptOrderLabel: "Pending Orders",
    DeliveredOrderLabel: "Completed Orders",
    InvoicedOrderLabel: "Invoiced Orders",
    DashboardOrdersLabel: "All Orders",
    LogoutLabel: "Logout",
    LogoutAlertTitle: "Logout",
    LogoutAlertBody: "Are you Sure You want to logout?",
    LogoutAlertSuccessButtonLabel: "Yes, I want To Logout",
    LogoutSuccessfulMessage: "Logout successful",
    BackButtonLabel: "Back",
    DashboardPageTitle: "My Dashboard",
    OrderDetailsPageTitle: "Order Details",
    DrawerDashboardLabel: "Dashboard",
    DrawerOrdersLabel: "Orders",
    DrawerSettingsLabel: "Settings",
    EmptyOrderListPageMessage: "Nothing Found Here",
    OrderNumberPrefix: "Order #",
    OrderDatePrefix: "Order Date : ",
    DenyOrderAlertTitle: "Deny Order",
    DenyOrderAlertBody: "Are you sure you want to deny this order?",
    DenyOrderAlertSuccessButtonLabel: "Yes, Deny this order",
    EmptyorderDetailsPageMessage: "How Did you land here ? \nThere\'s something wrong \nEither Go Back or if you are 100% sure this order belongs to you then you can contact the seller/administrator of the Website ",
    OrderNameLabelPrefix: "Order Name : ",
    OrderIdTextLabelPrefix: 'Order Id : ',
    PickingIdTextLabelPrefix: 'Picking Id : ',
    AssignDateTextLabelPrefix: 'Date & Time : ',
    OrderDeliveryAddressLabel: "Delivery Address ",
    OrderDetailsTextLabel: 'Order Details',
    CustomerDetailsTextLabel: 'Customer Details',
    ProductDetailsTextLabel: 'Item List',
    ProductNameLabel: 'Name : ',
    QtyToDeliverLabel: 'Qty : ',
    AcceptorderButtonLabel: "Accept Order",
    DenyOrderButtonLabel: "Deny Order",
    ShowonMapLabel: "Show on Map",
    MapRoutePageHeaderLabel: "Delivery Address Details",
    DeliveryLocationNotAvailable: "Sorry, Currently Delivery Location is not available",
    LocationPermissionTitle: 'Location Permission',
    LocationPermissionBody: "Location Permission Required in order to locate you on Map ",
    CurrentLocationNotAvailable: "Your Current Location is not available.",
    DeliveryAddressMapMarkerTitle: "Delivery Address",
    DeliveryBoyMapMarkerTitle: "My Location",
    StartNavigation: "Start Navigation",
    OrderDeliveredButtonLabel: "Set As Delivered",
    VerifyOTP: "Verify OTP",
    EnterDeliveryOTP: "Please Enter The Delivery OTP",
    DeliveryOTP: "Delivery OTP",
    OTPCannotBeEmptyLabel: "OTP cannot be empty",
    EnterValidOTPValue: "Enter Valid OTP Value",
    SettingsPageTitle: "Settings",
    AllpickingsPageTitle: "All Orders",
    OrderDetailsPageAmountLabel: "Amount : ",
    OrderDetailsPageStatusLabel: "Status",
    OrderDetailsTelephoneLabel: "Telephone",
    OrderDetailsMobileLabel: "Mobile",
    OrderDetailsEmailLabel: "Email",
    OrderDetailsSubtotalLabel: "Subtotal",
    OrderDetailsTaxLabel: "Tax",
    OrderDetailsGrandTotalLabel: "GrandTotal",
    AmountDueLabel: "Due Amount",
    TotalOrdersDeliveredLabel: "Order Delivered",
    TotalEarningsReceivedLabel: "Total Earning",
    TotalNumberOfBoxes: "Number of Boxes :",
    CustomerContact: "Customer Contact",
    arabic: "Arabic",
    english: "English",
    OrderReturned: "Order Retrned",
    MyOrders: 'My Orders',
    DELIVERY: 'DELIVERY',
    RETURN: 'RETURN',
    AssignedOrders: 'Assigned Orders',
    AcceptedOrders: 'Accepted Orders',
    CompletedOrders: 'Completed Orders',
    ReturnOrder: "Order Return",
    Order: "Order ",
    Return: "Return",
    OrderDate:"Date",
    VendorPos: "Vendor POs",
    RECEIVING:"RECEIVING"

}